### ISSUE TITLE
Zweiter Issue

### ISSUE THREAD

**Issue by florian25686** [florian25686/terraform-azurerm-appservice#2]
Issue mit längerem Thread, glaub ich. Vll hab ich auch keine Lust und es wird drum kürzer sein.

**Comment by florian25686** [comment]
Ich schreib jetzt mal was dazu

**Comment by florian25686** [comment]
Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.

**Comment by solarys-florian** [comment]
My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?
